"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const help_1 = require("./help");
exports.help = help_1.command;
const listproducts_1 = require("./listproducts");
exports.listproducts = listproducts_1.command;
const forgetme_1 = require("./forgetme");
exports.forgetme = forgetme_1.command;
const setproductenabled_1 = require("./setproductenabled");
exports.setproductenabled = setproductenabled_1.command;
const setautoverify_1 = require("./setautoverify");
exports.setautoverify = setautoverify_1.command;
const setautoapprove_1 = require("./setautoapprove");
exports.setautoapprove = setautoapprove_1.command;
const addfriend_1 = require("./addfriend");
exports.addfriend = addfriend_1.command;
const tours_1 = require("./tours");
exports.tours = tours_1.command;
const message_1 = require("./message");
exports.message = message_1.command;
const getconf_1 = require("./getconf");
exports.getconf = getconf_1.command;
//# sourceMappingURL=index.js.map